apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260628-004618-g4vexup6dun4-service
spec:
  selector:
    app: enterprise-system-20260628-004618-g4vexup6dun4
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
